//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visitor", Namespace="http://iterator")]
    [System.SerializableAttribute()]
    public partial class Visitor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Collumn9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn1 {
            get {
                return this.Collumn1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn1Field, value) != true)) {
                    this.Collumn1Field = value;
                    this.RaisePropertyChanged("Collumn1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn10 {
            get {
                return this.Collumn10Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn10Field, value) != true)) {
                    this.Collumn10Field = value;
                    this.RaisePropertyChanged("Collumn10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn11 {
            get {
                return this.Collumn11Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn11Field, value) != true)) {
                    this.Collumn11Field = value;
                    this.RaisePropertyChanged("Collumn11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn12 {
            get {
                return this.Collumn12Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn12Field, value) != true)) {
                    this.Collumn12Field = value;
                    this.RaisePropertyChanged("Collumn12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn13 {
            get {
                return this.Collumn13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn13Field, value) != true)) {
                    this.Collumn13Field = value;
                    this.RaisePropertyChanged("Collumn13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn14 {
            get {
                return this.Collumn14Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn14Field, value) != true)) {
                    this.Collumn14Field = value;
                    this.RaisePropertyChanged("Collumn14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn15 {
            get {
                return this.Collumn15Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn15Field, value) != true)) {
                    this.Collumn15Field = value;
                    this.RaisePropertyChanged("Collumn15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn2 {
            get {
                return this.Collumn2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn2Field, value) != true)) {
                    this.Collumn2Field = value;
                    this.RaisePropertyChanged("Collumn2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn3 {
            get {
                return this.Collumn3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn3Field, value) != true)) {
                    this.Collumn3Field = value;
                    this.RaisePropertyChanged("Collumn3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn4 {
            get {
                return this.Collumn4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn4Field, value) != true)) {
                    this.Collumn4Field = value;
                    this.RaisePropertyChanged("Collumn4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn5 {
            get {
                return this.Collumn5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn5Field, value) != true)) {
                    this.Collumn5Field = value;
                    this.RaisePropertyChanged("Collumn5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn6 {
            get {
                return this.Collumn6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn6Field, value) != true)) {
                    this.Collumn6Field = value;
                    this.RaisePropertyChanged("Collumn6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn7 {
            get {
                return this.Collumn7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn7Field, value) != true)) {
                    this.Collumn7Field = value;
                    this.RaisePropertyChanged("Collumn7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn8 {
            get {
                return this.Collumn8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn8Field, value) != true)) {
                    this.Collumn8Field = value;
                    this.RaisePropertyChanged("Collumn8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collumn9 {
            get {
                return this.Collumn9Field;
            }
            set {
                if ((object.ReferenceEquals(this.Collumn9Field, value) != true)) {
                    this.Collumn9Field = value;
                    this.RaisePropertyChanged("Collumn9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVisitorContract")]
    public interface IVisitorContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAll", ReplyAction="http://tempuri.org/IVisitorContract/GetAllResponse")]
        ClassLibrary1.ServiceReference1.Visitor[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAll", ReplyAction="http://tempuri.org/IVisitorContract/GetAllResponse")]
        System.Threading.Tasks.Task<ClassLibrary1.ServiceReference1.Visitor[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisitorContractChannel : ClassLibrary1.ServiceReference1.IVisitorContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitorContractClient : System.ServiceModel.ClientBase<ClassLibrary1.ServiceReference1.IVisitorContract>, ClassLibrary1.ServiceReference1.IVisitorContract {
        
        public VisitorContractClient() {
        }
        
        public VisitorContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitorContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitorContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitorContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClassLibrary1.ServiceReference1.Visitor[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary1.ServiceReference1.Visitor[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
