//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EX.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVisitorContract")]
    public interface IVisitorContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllVisitors", ReplyAction="http://tempuri.org/IVisitorContract/GetAllVisitorsResponse")]
        EX.Model.DbLayer.Visitor[] GetAllVisitors(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllVisitors", ReplyAction="http://tempuri.org/IVisitorContract/GetAllVisitorsResponse")]
        System.Threading.Tasks.Task<EX.Model.DbLayer.Visitor[]> GetAllVisitorsAsync(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllWithMess", ReplyAction="http://tempuri.org/IVisitorContract/GetAllWithMessResponse")]
        EX.Model.Repository.VisitorsWithMess GetAllWithMess(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllWithMess", ReplyAction="http://tempuri.org/IVisitorContract/GetAllWithMessResponse")]
        System.Threading.Tasks.Task<EX.Model.Repository.VisitorsWithMess> GetAllWithMessAsync(string m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisitorContractChannel : EX.Client.ServiceReference1.IVisitorContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitorContractClient : System.ServiceModel.ClientBase<EX.Client.ServiceReference1.IVisitorContract>, EX.Client.ServiceReference1.IVisitorContract {
        
        public VisitorContractClient() {
        }
        
        public VisitorContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitorContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitorContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitorContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EX.Model.DbLayer.Visitor[] GetAllVisitors(string m) {
            return base.Channel.GetAllVisitors(m);
        }
        
        public System.Threading.Tasks.Task<EX.Model.DbLayer.Visitor[]> GetAllVisitorsAsync(string m) {
            return base.Channel.GetAllVisitorsAsync(m);
        }
        
        public EX.Model.Repository.VisitorsWithMess GetAllWithMess(string m) {
            return base.Channel.GetAllWithMess(m);
        }
        
        public System.Threading.Tasks.Task<EX.Model.Repository.VisitorsWithMess> GetAllWithMessAsync(string m) {
            return base.Channel.GetAllWithMessAsync(m);
        }
    }
}
